name: 'Auto Release Milestone'
description: 'Drafts a GitHub release based on a closed milestone'
author: 'Mark Russell'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN uesd to authenticate the repository'
    required: true
outputs:
  pr-number:
    description: 'the number of the PR'
  pr-title:
    description: 'the title of the PR'
  pr-created-at:
    description: 'the stamp the PR was created at'
  pr-owner:
    description: 'the user creating the PR'
  pr-body:
    description: 'the body of the PR'
runs:
  using: docker
  image: 'Dockerfile'
  args: 
    - ${{ inputs.repo-token }}