name: Test
on:
  push:
    branches:
      - main
  milestone:
    types: [closed]
jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - name: Get Source
        uses: actions/checkout@v4
      - name: Setup Bats adn bats libs
        id: setup-bats
        uses: bats-core/bats-action@3
      - name: Test entrypoint.sh
        shell: bash
        env:
          BAST_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: bats tests
      - name: Create a release draft for a milestone
        id: create-release-draft
        uses: ./
        with: 
          repo-token: ${{ secrets.GITHUB_token }}
      - name: Print the RUL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: |
          echo ${{ steps.create-release-draft.outputs.release-url }}
          echo "# Release URL" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.create-release-draft.outputs.release-url }} >> $GITHUB_STEP_SUMMARY
