name: Test
on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main
jobs:
  test:
    name: test
#    runs-on: ubuntu-24.04
    runs-on: ubuntu-latest
    steps:
      - name: Get Source
        uses: actions/checkout@v4
      - name: Setup Bats adn bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.0
      - name: Test entrypoint.sh
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: |
          bats tests
      - name: process PR
        id: process-pr
        uses: ./
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Information from the PR
        if: steps.process-pr.outputs.pr-number != ''
        run: |
          echo ${{ steps.process-pr.outputs.pr-number }}
          echo "# Release URL" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.process-pr.outputs.pr-number }} >> $GITHUB_STEP_SUMMARY
